### ISSUE TITLE
Maximum number of partitions

### ISSUE THREAD

**Issue by fhtino** [MicrosoftDocs/common-data-model-and-service#40]
Is there any limit on the number of partitions (data files) I can create?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ce95c65c-2b6d-cca3-ff37-db6d5bfe818d
* Version Independent ID: 2e2cd63e-ae99-811d-3b09-ec3e54b700f2
* Content: [Metadata format - Common Data Model - Common Data Model](https://docs.microsoft.com/en-us/common-data-model/model-json)
* Content Source: [common-data-model/model-json.md](https://github.com/MicrosoftDocs/common-data-model-and-service/blob/master/common-data-model/model-json.md)
* Service: **common-data-model**
* GitHub Login: @theresapalmer
* Microsoft Alias: **tpalmer**

**Comment by JeffBern** [comment]
In theory yes, since the maximum storage account size is 2 PiB, but that doesn't help you much. I think in practice the limit is about the manageability of a model.json with millions of partition descriptions and the ability of the code to work with a giant list like that. What have you got in mind?  How about If I just say "no" :)
